/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {

    System.out.println("=== Starting Student Management App ===\n");

    // Option 1: Run Student class main directly
    System.out.println("Running Student.main()...");
    BankingMenu.main(args);
    System.out.println(new App().getGreeting());

  }
}
