/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    application
    id("com.diffplug.spotless") version "8.5.1"   // Latest as of May 2026
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.guava)
    implementation("io.github.thibaultmeyer:cuid:2.0.1")

}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("6.1.0")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "org.example.App"
}

// ==================== SPOTLESS CONFIG ====================
spotless {
    java {
        // Import ordering
        importOrder()
        removeUnusedImports()
            // or forbidWildcardImports() if you prefer

        // Optional but strongly recommended
        trimTrailingWhitespace()
        endWithNewline()
        leadingTabsToSpaces()        // or indentWithTabs() if you prefer

        // Code cleanup & formatting
        cleanthat()               // semantic cleanup (apply before formatter)
        googleJavaFormat()        // Google's formatter - very reliable

        // Extra nice-to-haves
        tableTestFormatter()
        formatAnnotations()

        // License header (uncomment & customize if needed)
        // licenseHeader("/* (C) \$YEAR */")
    }
}